<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0Hj2tR0\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0Hj2tR0/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container0Hj2tR0.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container0Hj2tR0\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container0Hj2tR0\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '0Hj2tR0',
    'container.build_id' => 'b2cc8221',
    'container.build_time' => 1614899536,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0Hj2tR0');
